import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import ScrollToTop from "@/components/ScrollToTop";
// import ScrollToTop from "@/app/components/ScrollToTop"; // Client component import

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "RamadanWeb - সেহরি ও ইফতারের সময়সূচি ২০২৬",
    template: "%s | RamadanWeb",
  },
  description:
    "রমজান ২০২৬-এর সঠিক সেহরি ও ইফতারের সময়সূচি দেখুন। পাশাপাশি প্রিমিয়াম ওয়েবসাইট ডেভেলপমেন্ট সার্ভিস নিন ৫০% ছাড়ে।",
  keywords: [
    "রমজান ২০২৬",
    "সেহরি সময়",
    "ইফতার সময়",
    "রমজান ক্যালেন্ডার",
    "ওয়েব ডেভেলপমেন্ট",
    "বাংলাদেশ",
  ],
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/favicon.ico.svg", sizes: "any" },
      { url: "/favicon", type: "image/svg+xml" },
    ],
  },
  authors: [{ name: "RamadanWeb Team" }],
  creator: "RamadanWeb",
  publisher: "RamadanWeb",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    title: "RamadanWeb - সেহরি ও ইফতারের সময়সূচি ২০২৬",
    description:
      "রমজান ২০২৬-এর সঠিক সেহরি ও ইফতারের সময়সূচি দেখুন। প্রিমিয়াম ওয়েবসাইট ডেভেলপমেন্ট সার্ভিস ৫০% ছাড়ে।",
    url: "https://ramadanweb.com",
    siteName: "RamadanWeb",
    images: [
      {
        url: "https://ramadanweb.com/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "RamadanWeb - রমজান ২০২৬",
      },
    ],
    locale: "bn_BD",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "RamadanWeb - সেহরি ও ইফতারের সময়সূচি ২০২৬",
    description:
      "রমজান ২০২৬-এর সঠিক সেহরি ও ইফতারের সময়সূচি দেখুন। প্রিমিয়াম ওয়েবসাইট ডেভেলপমেন্ট সার্ভিস ৫০% ছাড়ে।",
    images: ["https://ramadanweb.com/twitter-image.jpg"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  verification: {
    google: "your-google-verification-code",
  },
  category: "technology",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="bn" dir="ltr" className="scroll-smooth">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />

        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
        />

        {/* ✅ Favicon (bulletproof) */}
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        <link rel="icon" href="/favicon.svg" />

        <meta name="theme-color" content="#10b981" />
        <meta name="msapplication-TileColor" content="#10b981" />

        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=5"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gradient-to-br from-slate-50 via-white to-slate-100 dark:from-gray-900 dark:via-gray-800 dark:to-gray-900 font-sans`}
      >
        {/* Skip to main content link for accessibility */}
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 bg-amber-500 text-white px-4 py-2 rounded-lg z-50"
        >
          মূল কন্টেন্টে যান
        </a>

        {/* Main content */}
        <main id="main-content">{children}</main>

        {/* Toast notifications */}
        <Toaster
          position="top-right"
          richColors
          closeButton
          theme="system"
          toastOptions={{
            duration: 5000,
            className: "font-bangla",
          }}
        />

        {/* Scroll to top button - Client Component */}
        <ScrollToTop />
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { Toaster } from "@/components/ui/sonner";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//         <Toaster position="top-right" richColors />
//       </body>
//     </html>
//   );
// }
